name: Build and Test

on:
  pull_request:
  push:
    branches: [main, develop]

jobs:
  run:
    name: Run
    if: "!contains(github.event.pull_request.labels.*.name, 'Blocked: Fix Required')"
    uses: IngSoft-DA2/workflows/.github/workflows/reusable-build-test.yml@block-when-failure
    permissions: write-all
    with:
      solution-name: Test.sln
