name: Build and Test

on:
  pull_request:
  push:
    branches: [main, develop]

jobs:
  run:
    name: Run
    permissions: write-all
    uses: IngSoft-DA2/workflows/.github/workflows/reusable-build-test.yml@main
    with:
      solution-name: 'Test.sln'
