name: Code Analysis

on:
  pull_request:
  push:
    branches: [main, develop]

jobs:
  run:
    name: Run
    uses: CodeQuality-Uyu/workflows/.github/workflows/reusable-code-analysis.yml@main
    permissions: write-all
    with:
      solution-name: 'Test.sln'
