name: Code Analysis

on:
  pull_request:
  push:
    branches: [main, develop]

jobs:
  run:
    name: Run
    uses: IngSoft-DA2/workflows/.github/workflows/reusable-code-analysis.yml@block-when-failure
    permissions: write-all
    with:
      solution-name: 'Test.sln'
