name: Tag

on:
  push:
    branches: [main, develop]

jobs:
  run:
    name: Run
    uses: CodeQuality-Uyu/workflows/.github/workflows/reusable-tag.yml@main
    permissions: write-all
    with:
      mayor: main
      minor: develop
      patch: develop
